typography_spectrum: 0.11904025264084339
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.19765107962302864
  lightness: 0.6098762014880776
  saturation: 0.8893326581455767
  rhythmicContrast: 0.75166529067792
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.06539612310007215
analytics:
  google: null
  facebook: null
  twitter: null
name: lamommies
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: LA Mommies
description: 'A support group for moms. '
purpose: []
